export const DUMMY_STORE = {
  storeName: "Nara Modest",
  storeTagline: "Modest Wear Catalog",
  whatsappNumber: "6281234567890",
  instagramUsername: "naramodest",
  instagramUrl: "https://instagram.com/naramodest",
  address: "Sampit, Indonesia",
  heroTitle: "Elegan Setiap Hari",
  heroSubtitle: "Belanja koleksi hijab dan modest wear terbaru langsung via WhatsApp.",
  promoText: "Koleksi baru minggu ini sudah tersedia.",
  primaryColor: "#8B5E3C",
  seoTitle: "",
  seoDescription: "",
};

export const DUMMY_CATEGORIES = [
  { _id: "cat-1", title: "Pashmina", slug: "pashmina", order: 1 },
  { _id: "cat-2", title: "Bergo", slug: "bergo", order: 2 },
  { _id: "cat-3", title: "Abaya", slug: "abaya", order: 3 },
  { _id: "cat-4", title: "Aksesoris", slug: "aksesoris", order: 4 },
  { _id: "cat-5", title: "Bundling", slug: "bundling", order: 5 },
];

export const DUMMY_PRODUCTS = [
  {
    _id: "prod-1",
    name: "Pashmina Silk Nude",
    slug: "pashmina-silk-nude",
    category: { _id: "cat-1", title: "Pashmina", slug: "pashmina" },
    price: 75000,
    image: null,
    description: "Pashmina silk premium dengan warna nude elegan. Bahan lembut dan nyaman dipakai seharian.",
    isAvailable: true,
    isFeatured: true,
    sortOrder: 1,
  },
  {
    _id: "prod-2",
    name: "Pashmina Silk Mauve",
    slug: "pashmina-silk-mauve",
    category: { _id: "cat-1", title: "Pashmina", slug: "pashmina" },
    price: 75000,
    image: null,
    description: "Pashmina silk warna mauve yang cantik. Cocok untuk tampilan sehari-hari maupun acara formal.",
    isAvailable: true,
    isFeatured: false,
    sortOrder: 2,
  },
  {
    _id: "prod-3",
    name: "Bergo Maryam Cream",
    slug: "bergo-maryam-cream",
    category: { _id: "cat-2", title: "Bergo", slug: "bergo" },
    price: 89000,
    image: null,
    description: "Bergo Maryam warna cream yang versatile. Bahan voal premium anti-kusut.",
    isAvailable: true,
    isFeatured: true,
    sortOrder: 3,
  },
  {
    _id: "prod-4",
    name: "Bergo Daily Black",
    slug: "bergo-daily-black",
    category: { _id: "cat-2", title: "Bergo", slug: "bergo" },
    price: 79000,
    image: null,
    description: "Bergo hitam klasik untuk tampilan daily. Praktis dan elegan.",
    isAvailable: true,
    isFeatured: false,
    sortOrder: 4,
  },
  {
    _id: "prod-5",
    name: "Abaya Basic Hitam",
    slug: "abaya-basic-hitam",
    category: { _id: "cat-3", title: "Abaya", slug: "abaya" },
    price: 249000,
    image: null,
    description: "Abaya basic hitam dengan potongan A-line. Bahan crepe premium yang jatuh dan elegan.",
    isAvailable: true,
    isFeatured: true,
    sortOrder: 5,
  },
  {
    _id: "prod-6",
    name: "Tunik Linen Almond",
    slug: "tunik-linen-almond",
    category: { _id: "cat-3", title: "Abaya", slug: "abaya" },
    price: 189000,
    image: null,
    description: "Tunik linen warna almond yang adem dan casual. Cocok untuk aktivitas santai maupun kerja.",
    isAvailable: true,
    isFeatured: false,
    sortOrder: 6,
  },
  {
    _id: "prod-7",
    name: "Inner Ninja Premium",
    slug: "inner-ninja-premium",
    category: { _id: "cat-4", title: "Aksesoris", slug: "aksesoris" },
    price: 35000,
    image: null,
    description: "Inner ninja premium anti-licin. Bahan jersey lembut dan stretch.",
    isAvailable: true,
    isFeatured: false,
    sortOrder: 7,
  },
  {
    _id: "prod-8",
    name: "Scrunchie Premium",
    slug: "scrunchie-premium",
    category: { _id: "cat-4", title: "Aksesoris", slug: "aksesoris" },
    price: 25000,
    image: null,
    description: "Scrunchie satin premium. Tersedia dalam berbagai warna pilihan.",
    isAvailable: true,
    isFeatured: false,
    sortOrder: 8,
  },
  {
    _id: "prod-9",
    name: "Bundling Pashmina 3 Warna",
    slug: "bundling-pashmina-3-warna",
    category: { _id: "cat-5", title: "Bundling", slug: "bundling" },
    price: 199000,
    image: null,
    description: "Paket hemat 3 pashmina silk dengan warna berbeda. Lebih hemat dibanding beli satuan.",
    isAvailable: true,
    isFeatured: true,
    sortOrder: 9,
  },
  {
    _id: "prod-10",
    name: "Paket Daily Modest",
    slug: "paket-daily-modest",
    category: { _id: "cat-5", title: "Bundling", slug: "bundling" },
    price: 299000,
    image: null,
    description: "Paket lengkap untuk tampilan daily modest: 1 bergo + 1 inner ninja + 1 scrunchie.",
    isAvailable: true,
    isFeatured: false,
    sortOrder: 10,
  },
];
